CSE241_HATICE_SEVRA_GENC_1801042611:  main.cpp AbstractHex.cpp HexVector.cpp

	g++ -std=c++11 -o test main.cpp AbstractHex.cpp AbstractHex.h HexVector.cpp HexVector.h HexArray1D.cpp HexArray1D.h HexAdapter.cpp HexAdapter.h
	./test